#pragma config(Hubs,  S1, HTServo,  HTMotor,  HTMotor,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     compassSensor,  sensorVirtualCompass)
#pragma config(Sensor, S3,     lightSensor,    sensorLightActive)
#pragma config(Sensor, S4,     sonarSensor,    sensorSONAR)
#pragma config(Motor,  mtr_S1_C2_1,     leftMotor,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     rightMotor,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     motorF,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C1_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_6,    servo6,               tServoNone)

//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// NOTE: this is a modified version of a sample tank-drive script included with RobotC.
// This file was modified to work with one joystick by Brendan Gregos.



//#pragma debuggerWindows("joystickGame");
#include "JoystickDriver.c"
void wheelSpeed(int ls, int rs);
task main()
{

/* * * *        Joystick Codes          * * * */

               //Buttons

                       int buttonA = 2; // Bottom Button       |       Green

                       int buttonB = 3; // Right Button        |       Red

                       int buttonX = 1; // Left Button         |       Blue

                       int buttonY = 4; // Top Button          |       Yellow

               //Triggers

                       int triggerLT = 5; // Left Top

                       int triggerLB = 7; // Left Bottom

                       int triggerRT = 6; // Right Top

                       int triggerRB = 8; // Right Bottom

               //Center Buttoms

                       int centerL = 9;        // Back Button

                       int centerR = 10;       // Start Button

               //D-Pad

                       int dpad = joystick.joy1_TopHat; //D-Pad Value

                       // -1 is False | Values are 0-7

               //Analogue

                       int analogLeft = 11;    // Left Analogue Presses

                       int analogRight = 12;   // Right Analogue Presses

       /* * * *        End Joystick Codes      robit* * * */


	bNxtLCDStatusDisplay = false;
  //Integer variable that allows you to specify a "deadzone" where values (both positive or negative)
  //less than the threshold will be ignored.

	bool tank = false;
	int threshold = 5;
  //Loop Forever
	float yval = 0; //Out of 100 for motor speed
  float xval = 0; //Out of 100 for motor speed
  while(1)
  {

  	getJoystickSettings(joystick); //updates joystick placement
		//bool tjd = false; //Two Joystick Drive
  	//int ystick2=joystick.joy1_y2;
  	int ystick=joystick.joy1_y1; //this variable is set to the y position of the left analog stick
  	int xstick=joystick.joy1_x1; //this variable is set to the x position of the left analog stick
  	int ystickT=joystick.joy1_y2; //this variable is set to the y position of the left analog stick
  	int xstickT=joystick.joy1_x2; //this variable is set to the x position of the left analog stick
//robit//

  	if((xstick>=0&&xstick<=threshold) || (xstick<=0&&xstick>=(0-threshold))) 	{	xstick=0;		}
		if((ystick>=0&&ystick<=threshold) || (ystick<=0&&ystick>=(0-threshold))) 	{	ystick=0;		}
		if((xstickT>=0&&xstickT<=threshold) || (xstickT<=0&&xstickT>=(0-threshold))) 	{	xstickT=0;		}
		if((ystickT>=0&&ystickT<=threshold) || (ystickT<=0&&ystickT>=(0-threshold))) 	{	ystickT=0;		}


/*
to make beyond threshold fake values from 1 to 127
127 MAX
abs = absolute value:0, threshold to 127
////
if (abs>=threshold) --if threshold number is above or equal to threshold
	(abs-threshold)/(127-threshold)*127
		^^then porportionally make it so threshold+1 (in this case 11) is a value of 1
			likewise 127 stays 127

////
	test t = 10
abs = 50 (40)/(117)*127 == 43.4188
abs = 127 (117)/(117)*127 == 127
abs = 10 (0)/(117)*127 == 0



*/

  	int ystickL = (0-ystick);
  	int ystickTL = (0-ystickT);
  	int xstickL = (0-xstick);
  	int xstickTL = (0-xstickT);


		//int aa	=	(((ystickL)/127)*60)-((xstickT/127)*60); OLD CODE/Semi Working
		//int bb	=	(((ystick)/127)*60)-((xstickT/127)*60);
  	/*if(ystick == 0 && xstickT == 0) {
  		wheelSpeed(0, 0);
  	} else {*/
  		yval = 0; //Out of 100 for motor speed
  		xval = 0; //Out of 100 for motor speed

  		if(ystick > 0){
  			//Makes numbers not in threshold start from 1 versus threshold+1
  			yval = ( (ystick - threshold) * 100) / (127-threshold); //Makes numbers not in threshold start from 1 versus threshold+1
  		} else if (ystick < 0) {
  			yval = ( ((0 - ystick) - threshold ) * -100) / (127-threshold); //Makes numbers not in threshold start from 1 versus threshold+1
				//yval = ((((0-ystick)-threshold)/(127-threshold)*127)/127)*(0-100);//Same for negative yvalue
  		}


  		if(xstickT > 0){
  			xval = ( ((xstickT) - threshold ) * 100) / (127-threshold);
  			//xval = (((xstickT-threshold)/(127-threshold)*127)/127)*100; //Makes numbers not in threshold start from 1 versus threshold+1
  		} else if (xstickT < 0) {
  			//xval = ((((xstickT)-threshold)/(127-threshold)*127)/127)*(0-100);//Same for negative yvalue
  			xval = ( ((0 - xstickT) - threshold ) * -100) / (127-threshold);
  		}



	eraseDisplay();
	nxtDisplayString(3, "ystick %d@", yval);
	nxtDisplayString(4, "xstickT %d@", xval);



  		int sl	=	((yval)*0.60)-(xval*0.60);
			int sr	=	((yval)*0.60)-(xval*-0.60);//0- switch
  		wheelSpeed(sl, sr);
  	/*}*/
		nxtDisplayString(1, "Left Motor %d@", sl);
	nxtDisplayString(2, "Right Motor %d@", sr);

    /*if(joy1Btn(1)==1){
  		motor[leftMotor] = -10;
  		motor[rightMotor] = 10;
  		wait1Msec(250);
  		motor[leftMotor] = 0;
  		motor[rightMotor] = 0;
  	}*/




//nxtDisplayString(3, "stick1y %d", ystick);
  }
}
void wheelSpeed(int ls, int rs) {
	motor[leftMotor] = -ls;
	motor[rightMotor] = rs;//MAYBE NEEDS TO BE SWITCHED - or OTHER ONE
}
